### ISSUE TITLE
Failure to compile on Mac OS Big Sur 11.6.5

### ISSUE THREAD

**Issue by winitzki** [xdevs23/busybox-osx#1]
Compilation fails with:

```
libbb/inet_common.c:31:6: error: implicit declaration of function 'inet_aton' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        if (inet_aton(name, &s_in->sin_addr)) {
            ^
libbb/inet_common.c:117:18: error: implicit declaration of function 'inet_ntoa' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                return xstrdup(inet_ntoa(s_in->sin_addr));
                               ^
libbb/inet_common.c:117:18: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
                return xstrdup(inet_ntoa(s_in->sin_addr));
                               ^~~~~~~~~~~~~~~~~~~~~~~~~
include/libbb.h:648:27: note: passing argument to parameter 's' here
char *xstrdup(const char *s) FAST_FUNC RETURNS_MALLOC;
                          ^
libbb/inet_common.c:153:18: warning: incompatible integer to pointer conversion passing 'int' to parameter of type 'const char *' [-Wint-conversion]
                name = xstrdup(inet_ntoa(s_in->sin_addr));
                               ^~~~~~~~~~~~~~~~~~~~~~~~~
include/libbb.h:648:27: note: passing argument to parameter 's' here
char *xstrdup(const char *s) FAST_FUNC RETURNS_MALLOC;
                          ^
libbb/inet_common.c:204:3: error: implicit declaration of function 'inet_ntop' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                inet_ntop(AF_INET6, &sin6->sin6_addr, name, sizeof(name));
                ^
2 warnings and 3 errors generated.
make[1]: *** [libbb/inet_common.o] Error 1
make: *** [libbb] Error 2
```

**Comment by xdevs23** [comment]
I'm sorry, this is no longer maintained and there are no plans to port it for newer macOS versions.
